name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: "${{secrets.REPO_AND_PACKAGES_TOKEN}}"
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic mvg-info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "if master: fail if there is already a tag for this version"
        if: github.ref == 'refs/heads/master'
        run:  |
          . <(java -jar ~/buildtools.jar)
          errorIfVersionTagExists

      - name: "prepare ant"
        run:  |
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.maven_repository=$HOME/.m2/repository
          EOF

      - name: "(re)generate some files"
        run:  |
          . <(java -jar ~/buildtools.jar)
          generateAll
          correctEols
          correctHeaders header

      - name: "push changes back to github"
        run:  |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub

      - name: "download dependencies (as mentioned in pom)"
        run:  |
          . <(java -jar ~/buildtools.jar)
          set -x
          getAllDependencies "${{secrets.SCALEWAY_ACCESS_KEY}}" "${{secrets.SCALEWAY_SECRET_KEY}}"
          installJunitlauncher
          ls -lR /tmp/artifacts/tmp-artifacts/lib /tmp/artifacts/tmp-artifacts/trigger | sed 's/^/@!@! /'
          (cd /tmp/artifacts/tmp-artifacts; git status) | sed 's/^/~!@! /'

      - name: "build"
        run:  ant

      - name: "test"
        run:  |
          if ! ant test; then
            for i in TEST-*.xml; do
              echo "=============== $i"
              sed "s/^/>> /" $i
            done
            exit 42
          fi

      - name: "generate javadoc"
        run:  ant javadoc

      - name: "if master: tag with version"
        if: github.ref == 'refs/heads/master'
        run:  |
          . <(java -jar ~/buildtools.jar)
          setVersionTag

      - name: "publish action-artifact jar"
        uses: actions/upload-artifact@v1
        with:
          name: dclareForJava.jar
          path: out/artifacts/dclareForJava.jar

      - name: "publish action-artifact sources"
        uses: actions/upload-artifact@v1
        with:
          name: dclareForJava-sources.jar
          path: out/artifacts/dclareForJava-sources.jar

      - name: "publish action-artifact javadoc"
        uses: actions/upload-artifact@v1
        with:
          name: dclareForJava-javadoc.jar
          path: out/artifacts/dclareForJava-javadoc.jar

      - name: "publish action-artifact test-results"
        uses: actions/upload-artifact@v1
        with:
          name: dclareForJava-testresults.jar
          path: out/artifacts/dclareForJava-testresults.jar

      - name: "publish jars on S3"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          access_key     : "${{secrets.SCALEWAY_ACCESS_KEY}}"
          secret_key     : "${{secrets.SCALEWAY_SECRET_KEY}}"
          trigger_token  : "${{secrets.RETRIGGER_TOKEN}}"
          bucket         : "mvg-artifacts"
          cmd            : "put"
          local_dir      : "out/artifacts"
          s3_dir_branched: "/"

      - name: "if master: publish maven-artifacts (jar/pom/sources/javadoc)"
        uses: ModelingValueGroup/upload-maven-package-action@master
        if  : github.ref == 'refs/heads/master'
        with:
          file : "out/artifacts/dclareForJava.jar"
